# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `oauth2` gem.
# Please instead update this file by running `bin/tapioca gem oauth2`.


# The namespace of this library
#
# This module is the entry point and top-level namespace for the oauth2 gem.
# It exposes configuration, constants, and requires the primary public classes.
#
# pkg:gem/oauth2#lib/oauth2/version.rb:3
module OAuth2
  private

  # Configure global library behavior.
  #
  # Yields the mutable configuration object so callers can update settings.
  #
  # @return [void]
  # @yieldparam config [SnakyHash::SymbolKeyed] the configuration object
  #
  # pkg:gem/oauth2#lib/oauth2.rb:72
  def configure; end

  class << self
    # Access the current configuration.
    #
    # Prefer using {OAuth2.configure} to mutate configuration.
    #
    # @return [SnakyHash::SymbolKeyed]
    #
    # pkg:gem/oauth2#lib/oauth2.rb:63
    def config; end

    # Configure global library behavior.
    #
    # Yields the mutable configuration object so callers can update settings.
    #
    # @return [void]
    # @yieldparam config [SnakyHash::SymbolKeyed] the configuration object
    #
    # pkg:gem/oauth2#lib/oauth2.rb:75
    def configure; end
  end
end

# pkg:gem/oauth2#lib/oauth2/access_token.rb:19
class OAuth2::AccessToken
  include ::OAuth2::FilteredAttributes
  extend ::OAuth2::FilteredAttributes::ClassMethods

  # Initialize an AccessToken
  #
  # @example Verb-dependent Hash mode
  #   # Send token in query for GET, in header for POST/DELETE, in body for PUT/PATCH
  #   OAuth2::AccessToken.new(client, token, mode: {get: :query, post: :header, delete: :header, put: :body, patch: :body})
  # @note For "soon-to-expire"/"clock-skew" functionality see the `:expires_latency` option.
  # @note If no token is provided, the AccessToken will be considered invalid.
  #   This is to prevent the possibility of a token being accidentally
  #   created with no token value.
  #   If you want to create an AccessToken with no token value,
  #   you can pass in an empty string or nil for the token value.
  #   If you want to create an AccessToken with no token value and
  #   no refresh token, you can pass in an empty string or nil for the
  #   token value and nil for the refresh token, and `raise_errors: false`.
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @param client [Client] the OAuth2::Client instance
  # @param opts [Hash] the options to create the Access Token with
  # @param token [String] the Access Token value (optional, may not be used in refresh flows)
  # @return [AccessToken] a new instance of AccessToken
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:148
  def initialize(client, token, opts = T.unsafe(nil)); end

  # Indexer to additional params present in token response
  #
  # @param key [String] entry key to Hash
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:186
  def [](key); end

  # Returns the value of attribute client.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:26
  def client; end

  # Make a DELETE request with the Access Token
  #
  # @see AccessToken#request
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:368
  def delete(path, opts = T.unsafe(nil), &block); end

  # Check if token is expired
  #
  # @return [Boolean] true if the token is expired, false otherwise
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:200
  def expired?; end

  # Whether the token expires
  #
  # @return [Boolean]
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:193
  def expires?; end

  # Returns the value of attribute expires_at.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:26
  def expires_at; end

  # Returns the value of attribute expires_in.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:26
  def expires_in; end

  # Returns the value of attribute expires_latency.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:26
  def expires_latency; end

  # Make a GET request with the Access Token
  #
  # @see AccessToken#request
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:340
  def get(path, opts = T.unsafe(nil), &block); end

  # Get the headers hash (includes Authorization token)
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:373
  def headers; end

  # Returns the value of attribute options.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:27
  def options; end

  # Sets the attribute options
  #
  # @param value the value to set the attribute options to.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:27
  def options=(_arg0); end

  # Returns the value of attribute params.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:26
  def params; end

  # Make a PATCH request with the Access Token
  #
  # @see AccessToken#request
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:361
  def patch(path, opts = T.unsafe(nil), &block); end

  # Make a POST request with the Access Token
  #
  # @see AccessToken#request
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:347
  def post(path, opts = T.unsafe(nil), &block); end

  # Make a PUT request with the Access Token
  #
  # @see AccessToken#request
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:354
  def put(path, opts = T.unsafe(nil), &block); end

  # Refreshes the current Access Token
  #
  # @note current token's options are carried over to the new AccessToken
  # @param access_token_opts [Hash] options that will be passed to the AccessToken initialization
  # @param params [Hash] additional params to pass to the refresh token request
  # @raise [OAuth2::Error]
  # @return [OAuth2::AccessToken] a new AccessToken instance
  # @yield [opts] The block to modify the refresh token request options
  # @yieldparam opts [Hash] The options hash that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:215
  def refresh(params = T.unsafe(nil), access_token_opts = T.unsafe(nil), &block); end

  # Refreshes the current Access Token
  # A compatibility alias
  #
  # @note current token's options are carried over to the new AccessToken
  # @note does not modify the receiver, so bang is not the default method
  # @param access_token_opts [Hash] options that will be passed to the AccessToken initialization
  # @param params [Hash] additional params to pass to the refresh token request
  # @raise [OAuth2::Error]
  # @return [OAuth2::AccessToken] a new AccessToken instance
  # @yield [opts] The block to modify the refresh token request options
  # @yieldparam opts [Hash] The options hash that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:231
  def refresh!(params = T.unsafe(nil), access_token_opts = T.unsafe(nil), &block); end

  # Returns the value of attribute refresh_token.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:27
  def refresh_token; end

  # Sets the attribute refresh_token
  #
  # @param value the value to set the attribute refresh_token to.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:27
  def refresh_token=(_arg0); end

  # Make a request with the Access Token
  #
  # @option opts
  # @option opts
  # @option opts
  # @param opts [Hash] the options to make the request with
  # @param path [String] the HTTP URL path of the request
  # @param verb [Symbol] the HTTP request method
  # @return [OAuth2::Response] the response from the request
  # @see OAuth2::Client#request
  # @yield [req] The block to modify the request
  # @yieldparam req [Faraday::Request] The request object that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:332
  def request(verb, path, opts = T.unsafe(nil), &block); end

  # Returns the value of attribute response.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:27
  def response; end

  # Sets the attribute response
  #
  # @param value the value to set the attribute response to.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:27
  def response=(_arg0); end

  # Revokes the token at the authorization server
  #
  # @api public
  # @note If the token passed to the request
  #   is an access token, the server MAY revoke the respective refresh
  #   token as well.
  # @note If the token passed to the request
  #   is a refresh token and the authorization server supports the
  #   revocation of access tokens, then the authorization server SHOULD
  #   also invalidate all access tokens based on the same authorization
  #   grant
  # @note If the server responds with HTTP status code 503, your code must
  #   assume the token still exists and may retry after a reasonable delay.
  #   The server may include a "Retry-After" header in the response to
  #   indicate how long the service is expected to be unavailable to the
  #   requesting client.
  # @option params
  # @option params
  # @param params [Hash] additional parameters to be sent during revocation
  # @raise [OAuth2::Error] if token_type_hint is invalid or the specified token is not available
  # @return [OAuth2::Response] OAuth2::Response instance
  # @see https://datatracker.ietf.org/doc/html/rfc7009
  # @see https://datatracker.ietf.org/doc/html/rfc7009#section-2.1
  # @yield [req] The block is passed the request being made, allowing customization
  # @yieldparam req [Faraday::Request] The request object that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:264
  def revoke(params = T.unsafe(nil), &block); end

  # Revokes the token at the authorization server
  # A compatibility alias
  #
  # @api public
  # @note If the token passed to the request
  #   is an access token, the server MAY revoke the respective refresh
  #   token as well.
  # @note If the token passed to the request
  #   is a refresh token and the authorization server supports the
  #   revocation of access tokens, then the authorization server SHOULD
  #   also invalidate all access tokens based on the same authorization
  #   grant
  # @note If the server responds with HTTP status code 503, your code must
  #   assume the token still exists and may retry after a reasonable delay.
  #   The server may include a "Retry-After" header in the response to
  #   indicate how long the service is expected to be unavailable to the
  #   requesting client.
  # @note does not modify the receiver, so bang is not the default method
  # @option params
  # @option params
  # @param params [Hash] additional parameters to be sent during revocation
  # @raise [OAuth2::Error] if token_type_hint is invalid or the specified token is not available
  # @return [OAuth2::Response] OAuth2::Response instance
  # @see https://datatracker.ietf.org/doc/html/rfc7009
  # @see https://datatracker.ietf.org/doc/html/rfc7009#section-2.1
  # @yield [req] The block is passed the request being made, allowing customization
  # @yieldparam req [Faraday::Request] The request object that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:291
  def revoke!(params = T.unsafe(nil), &block); end

  # Convert AccessToken to a hash which can be used to rebuild itself with AccessToken.from_hash
  #
  # @note Don't return expires_latency because it has already been deducted from expires_at
  # @return [Hash] a hash of AccessToken property values
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:298
  def to_hash; end

  # Returns the value of attribute token.
  #
  # pkg:gem/oauth2#lib/oauth2/access_token.rb:26
  def token; end

  private

  # pkg:gem/oauth2#lib/oauth2/access_token.rb:379
  def configure_authentication!(opts, verb); end

  # pkg:gem/oauth2#lib/oauth2/access_token.rb:414
  def convert_expires_at(expires_at); end

  class << self
    # Initializes an AccessToken from a Hash
    #
    # @example
    #   hash = { 'access_token' => 'token_value', 'refresh_token' => 'refresh_value' }
    #   access_token = OAuth2::AccessToken.from_hash(client, hash)
    # @note The method will use the first found token key in the following order:
    #   'access_token', 'id_token', 'token' (or their symbolic versions)
    # @note If multiple token keys are present, a warning will be issued unless
    #   OAuth2.config.silence_extra_tokens_warning is true
    # @note If no token keys are present, a warning will be issued unless
    #   OAuth2.config.silence_no_tokens_warning is true
    # @note For "soon-to-expire"/"clock-skew" functionality see the `:expires_latency` option.
    # @note If snaky key conversion is being used, token_name needs to match the converted key.
    # @option hash
    # @option hash
    # @option hash
    # @option hash
    # @option hash
    # @option hash
    # @option hash
    # @param client [OAuth2::Client] the OAuth2::Client instance
    # @param hash [Hash] a hash containing the token and other properties
    # @return [OAuth2::AccessToken] the initialized AccessToken
    #
    # pkg:gem/oauth2#lib/oauth2/access_token.rb:57
    def from_hash(client, hash); end

    # Initializes an AccessToken from a key/value application/x-www-form-urlencoded string
    #
    # @param client [Client] the OAuth2::Client instance
    # @param kvform [String] the application/x-www-form-urlencoded string
    # @return [AccessToken] the initialized AccessToken
    #
    # pkg:gem/oauth2#lib/oauth2/access_token.rb:90
    def from_kvform(client, kvform); end

    private

    # Having too many is sus, and may lead to bugs. Having none is fine (e.g. refresh flow doesn't need a token).
    #
    # pkg:gem/oauth2#lib/oauth2/access_token.rb:97
    def extra_tokens_warning(supported_keys, key); end

    # pkg:gem/oauth2#lib/oauth2/access_token.rb:104
    def no_tokens_warning(hash, key); end
  end
end

# pkg:gem/oauth2#lib/oauth2/access_token.rb:20
OAuth2::AccessToken::TOKEN_KEYS_STR = T.let(T.unsafe(nil), Array)

# pkg:gem/oauth2#lib/oauth2/access_token.rb:21
OAuth2::AccessToken::TOKEN_KEYS_SYM = T.let(T.unsafe(nil), Array)

# pkg:gem/oauth2#lib/oauth2/access_token.rb:22
OAuth2::AccessToken::TOKEN_KEY_LOOKUP = T.let(T.unsafe(nil), Array)

# Builds and applies client authentication to token and revoke requests.
#
# Depending on the selected mode, credentials are applied as Basic Auth
# headers, request body parameters, or only the client_id is sent (TLS).
#
# pkg:gem/oauth2#lib/oauth2/authenticator.rb:10
class OAuth2::Authenticator
  include ::OAuth2::FilteredAttributes
  extend ::OAuth2::FilteredAttributes::ClassMethods

  # Create a new Authenticator
  #
  # @param id [String, nil] Client identifier
  # @param mode [Symbol, String] Authentication mode
  # @param secret [String, nil] Client secret
  # @return [Authenticator] a new instance of Authenticator
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:24
  def initialize(id, secret, mode); end

  # Apply the request credentials used to authenticate to the Authorization Server
  #
  # Depending on the configuration, this might be as request params or as an
  # Authorization header.
  #
  # User-provided params and header take precedence.
  #
  # @param params [Hash] a Hash of params for the token endpoint
  # @return [Hash] params amended with appropriate authentication details
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:39
  def apply(params); end

  # @return [Symbol, String] Authentication mode (e.g., :basic_auth, :request_body, :tls_client_auth, :private_key_jwt)
  # @return [String, nil] Client identifier
  # @return [String, nil] Client secret (filtered in inspected output)
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:16
  def id; end

  # @return [Symbol, String] Authentication mode (e.g., :basic_auth, :request_body, :tls_client_auth, :private_key_jwt)
  # @return [String, nil] Client identifier
  # @return [String, nil] Client secret (filtered in inspected output)
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:16
  def mode; end

  # @return [Symbol, String] Authentication mode (e.g., :basic_auth, :request_body, :tls_client_auth, :private_key_jwt)
  # @return [String, nil] Client identifier
  # @return [String, nil] Client secret (filtered in inspected output)
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:16
  def secret; end

  private

  # Adds an `Authorization` header with Basic Auth credentials if and only if
  # it is not already set in the params.
  #
  # @param params [Hash] Request parameters (may include :headers)
  # @return [Hash] Updated parameters with Authorization header
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:93
  def apply_basic_auth(params); end

  # When using schemes that don't require the client_secret to be passed (e.g., TLS Client Auth),
  # we don't want to send the secret
  #
  # @param params [Hash] Request parameters
  # @return [Hash] Updated parameters including only client_id
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:82
  def apply_client_id(params); end

  # Adds client_id and client_secret request parameters if they are not
  # already set.
  #
  # @param params [Hash] Request parameters
  # @return [Hash] Updated parameters including client_id and client_secret
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:70
  def apply_params_auth(params); end

  # Build the Basic Authorization header.
  #
  # @return [Hash] Header hash containing the Authorization entry
  # @see https://datatracker.ietf.org/doc/html/rfc2617#section-2
  #
  # pkg:gem/oauth2#lib/oauth2/authenticator.rb:103
  def basic_auth_header; end

  class << self
    # Encodes a Basic Authorization header value for the provided credentials.
    #
    # @param password [String] The client secret
    # @param user [String] The client identifier
    # @return [String] The value to use for the Authorization header
    #
    # pkg:gem/oauth2#lib/oauth2/authenticator.rb:59
    def encode_basic_auth(user, password); end
  end
end

# The OAuth2::Client class
#
# pkg:gem/oauth2#lib/oauth2/client.rb:20
class OAuth2::Client
  include ::OAuth2::FilteredAttributes
  extend ::OAuth2::FilteredAttributes::ClassMethods

  # Initializes a new OAuth2::Client instance using the Client ID and Client Secret registered to your application.
  #
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @param client_id [String] the client_id value
  # @param client_secret [String] the client_secret value
  # @param options [Hash] the options to configure the client
  # @return [Client] a new instance of Client
  # @yield [builder] The Faraday connection builder
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:50
  def initialize(client_id, client_secret, options = T.unsafe(nil), &block); end

  # The Assertion strategy
  #
  # This allows for assertion-based authentication where an identity provider
  # asserts the identity of the user or client application seeking access.
  #
  # @return [OAuth2::Strategy::Assertion] the initialized Assertion strategy
  # @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-assertions-01#section-4.1
  # @see http://datatracker.ietf.org/doc/html/rfc7521
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:314
  def assertion; end

  # The Authorization Code strategy
  #
  # @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-15#section-4.1
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:280
  def auth_code; end

  # The authorize endpoint URL of the OAuth2 provider
  #
  # @param params [Hash] additional query parameters
  # @return [String] the constructed authorize URL
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:102
  def authorize_url(params = T.unsafe(nil)); end

  # The Client Credentials strategy
  #
  # @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-15#section-4.4
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:301
  def client_credentials; end

  # The Faraday connection object
  #
  # @return [Faraday::Connection] the initialized Faraday connection
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:85
  def connection; end

  # Sets the attribute connection
  #
  # @param value the value to set the attribute connection to.
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:28
  def connection=(_arg0); end

  # Retrieves an access token from the token endpoint using the specified parameters
  #
  # @example
  #   client.get_token(
  #   'grant_type' => 'authorization_code',
  #   'code' => 'auth_code_value',
  #   'headers' => {'Authorization' => 'Basic ...'}
  #   )
  # @note The extract_access_token parameter is deprecated and will be removed in oauth2 v3.
  #   Use access_token_class on initialization instead.
  # @param access_token_opts [Hash] options that will be passed to the AccessToken initialization
  # @param extract_access_token [Proc] (deprecated) a proc that can extract the access token from the response
  # @param params [Hash] a Hash of params for the token endpoint
  #   * params can include a 'headers' key with a Hash of request headers
  #   * params can include a 'parse' key with the Symbol name of response parsing strategy (default: :automatic)
  #   * params can include a 'snaky' key to control snake_case conversion (default: false)
  # @return [AccessToken, nil] the initialized AccessToken instance, or nil if token extraction fails
  #   and raise_errors is false
  # @yield [opts] The block is passed the options being used to make the request
  # @yieldparam opts [Hash] options being passed to the http library
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:208
  def get_token(params, access_token_opts = T.unsafe(nil), extract_access_token = T.unsafe(nil), &block); end

  # The HTTP Method of the request
  #
  # @return [Symbol] HTTP verb, one of [:get, :post, :put, :delete]
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:270
  def http_method; end

  # Returns the value of attribute id.
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:26
  def id; end

  # The Implicit strategy
  #
  # @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-26#section-4.2
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:287
  def implicit; end

  # Returns the value of attribute options.
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:27
  def options; end

  # Sets the attribute options
  #
  # @param value the value to set the attribute options to.
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:27
  def options=(_arg0); end

  # The Resource Owner Password Credentials strategy
  #
  # @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-15#section-4.3
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:294
  def password; end

  # The redirect_uri parameters, if configured
  #
  # The redirect_uri query parameter is OPTIONAL (though encouraged) when
  # requesting authorization. If it is provided at authorization time it MUST
  # also be provided with the token exchange request.
  #
  # OAuth 2.1 note: Authorization Servers must compare redirect URIs using exact string matching.
  # This client simply forwards the configured redirect_uri; the exact-match validation happens server-side.
  #
  # Providing :redirect_uri to the OAuth2::Client instantiation will take
  # care of managing this.
  #
  # @api semipublic
  # @return [Hash] the params to add to a request or URL
  # @see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-13
  # @see https://datatracker.ietf.org/doc/html/rfc6749#section-10.6
  # @see https://datatracker.ietf.org/doc/html/rfc6749#section-4.1
  # @see https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3
  # @see https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.1
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:339
  def redirection_params; end

  # Makes a request relative to the specified site root.
  #
  # Updated HTTP 1.1 specification (IETF RFC 7231) relaxed the original constraint (IETF RFC 2616),
  #   allowing the use of relative URLs in Location headers.
  #
  # @option req_opts
  # @option req_opts
  # @option req_opts
  # @option req_opts
  # @option req_opts
  # @option req_opts
  # @param req_opts [Hash] the options to make the request with
  # @param url [String] URL path of request
  # @param verb [Symbol] one of [:get, :post, :put, :delete]
  # @return [OAuth2::Response] the response from the request
  # @see Faraday::Connection#run_request
  # @see https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.2
  # @yield [req] The block is passed the request being made, allowing customization
  # @yieldparam req [Faraday::Request] The request object that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:146
  def request(verb, url, req_opts = T.unsafe(nil), &block); end

  # Makes a request to revoke a token at the authorization server
  #
  # @api public
  # @note If the token passed to the request
  #   is an access token, the server MAY revoke the respective refresh
  #   token as well.
  # @note If the token passed to the request
  #   is a refresh token and the authorization server supports the
  #   revocation of access tokens, then the authorization server SHOULD
  #   also invalidate all access tokens based on the same authorization
  #   grant
  # @note If the server responds with HTTP status code 503, your code must
  #   assume the token still exists and may retry after a reasonable delay.
  #   The server may include a "Retry-After" header in the response to
  #   indicate how long the service is expected to be unavailable to the
  #   requesting client.
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash] additional parameters for the token revocation
  # @param token [String] The token to be revoked
  # @param token_type_hint [String, nil] A hint about the type of the token being revoked (e.g., 'access_token' or 'refresh_token')
  # @return [OAuth2::Response] OAuth2::Response instance
  # @see https://datatracker.ietf.org/doc/html/rfc7009
  # @see https://datatracker.ietf.org/doc/html/rfc7009#section-2.1
  # @yield [req] The block is passed the request being made, allowing customization
  # @yieldparam req [Faraday::Request] The request object that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:257
  def revoke_token(token, token_type_hint = T.unsafe(nil), params = T.unsafe(nil), &block); end

  # The revoke endpoint URL of the OAuth2 provider
  #
  # @param params [Hash, nil] additional query parameters
  # @return [String] the constructed revoke URL
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:119
  def revoke_url(params = T.unsafe(nil)); end

  # Returns the value of attribute secret.
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:26
  def secret; end

  # Returns the value of attribute site.
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:26
  def site; end

  # Set the site host
  #
  # @param value [String] the OAuth2 provider site host
  # @return [String] the site host value
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:77
  def site=(value); end

  # The token endpoint URL of the OAuth2 provider
  #
  # @param params [Hash, nil] additional query parameters
  # @return [String] the constructed token URL
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:111
  def token_url(params = T.unsafe(nil)); end

  private

  # Returns the authenticator object
  #
  # @return [Authenticator] the initialized Authenticator
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:471
  def authenticator; end

  # Creates an access token instance from response data using the specified token class
  #
  # @api private
  # @note If the access token class responds to response=, the full response object will be set
  # @param access_token_class [Class] the class that should be used to create access token instances
  # @param access_token_opts [Hash] additional options to pass to the AccessToken initialization
  # @param response [OAuth2::Response] the OAuth2::Response from the token endpoint
  # @return [AccessToken] an initialized AccessToken instance with response data
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:537
  def build_access_token(response, access_token_opts, access_token_class); end

  # Builds an access token using a legacy extraction proc
  #
  # @api private
  # @deprecated Use {#build_access_token} instead
  # @param access_token_opts [Hash] additional options to pass to the access token extraction
  # @param extract_access_token [Proc] a proc that takes client and token hash as arguments
  #   and returns an access token instance
  # @param response [OAuth2::Response] the OAuth2::Response from the token endpoint
  # @return [AccessToken, nil] the access token instance if extraction succeeds,
  #   nil if any error occurs during extraction
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:556
  def build_access_token_legacy(response, access_token_opts, extract_access_token); end

  # Executes an HTTP request with error handling and response processing
  #
  # @api private
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @param opts [Hash] the request options
  # @param url [String] the URL for the request
  # @param verb [Symbol] the HTTP method to use (:get, :post, :put, :delete)
  # @raise [OAuth2::ConnectionError] when there's a network error
  # @raise [OAuth2::TimeoutError] when the request times out
  # @return [OAuth2::Response] the response wrapped in an OAuth2::Response object
  # @yield [req] gives access to the request object before sending
  # @yieldparam req [Faraday::Request] the request object that can be modified
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:444
  def execute_request(verb, url, opts = T.unsafe(nil)); end

  # pkg:gem/oauth2#lib/oauth2/client.rb:565
  def oauth_debug_logging(builder); end

  # Processes request parameters and transforms them into request options
  #
  # @api private
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash] the request parameters to process
  # @return [Hash] the processed request options
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:361
  def params_to_req_opts(params); end

  # Parses the OAuth response and builds an access token using the configured access token class
  #
  # @api private
  # @param access_token_opts [Hash] options to pass to the AccessToken initialization
  # @param response [OAuth2::Response] the OAuth2::Response from the token endpoint
  # @raise [OAuth2::Error] if the response is empty/invalid and the raise_errors option is true
  # @return [AccessToken] the initialized AccessToken instance
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:512
  def parse_response(response, access_token_opts); end

  # Parses the OAuth response and builds an access token using legacy extraction method
  #
  # @api private
  # @deprecated Use {#parse_response} instead
  # @param access_token_opts [Hash] options to pass to the AccessToken initialization
  # @param extract_access_token [Proc] proc to extract the access token from response
  # @param response [OAuth2::Response] the OAuth2::Response from the token endpoint
  # @raise [OAuth2::Error] if response indicates an error and raise_errors option is true
  # @return [AccessToken, nil] the initialized AccessToken if successful, nil if extraction fails
  #   and raise_errors option is false
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:489
  def parse_response_legacy(response, access_token_opts, extract_access_token); end

  # Processes and transforms parameters for OAuth requests
  #
  # @api private
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash] the input parameters to process
  # @return [Array<(Symbol, Boolean, Class, Symbol, Hash, Hash)>] Returns an array containing:
  #   - parse strategy (Symbol)
  #   - snaky flag for response key transformation (Boolean)
  #   - hash class for snake_case conversion (Class)
  #   - token method override (Symbol, nil)
  #   - processed parameters (Hash)
  #   - HTTP headers (Hash)
  #
  # pkg:gem/oauth2#lib/oauth2/client.rb:406
  def parse_snaky_params_headers(params); end
end

# pkg:gem/oauth2#lib/oauth2/client.rb:22
OAuth2::Client::RESERVED_PARAM_KEYS = T.let(T.unsafe(nil), Array)

# pkg:gem/oauth2#lib/oauth2/client.rb:21
OAuth2::Client::RESERVED_REQ_KEYS = T.let(T.unsafe(nil), Array)

# pkg:gem/oauth2#lib/oauth2/client.rb:16
class OAuth2::ConnectionError < ::Faraday::ConnectionFailed; end

# Default configuration values for the oauth2 library.
#
# @example Toggle warnings
#   OAuth2.configure do |config|
#   config[:silence_extra_tokens_warning] = false
#   config[:silence_no_tokens_warning] = false
#   end
# @return [SnakyHash::SymbolKeyed] A mutable Hash-like config with symbol keys
#
# pkg:gem/oauth2#lib/oauth2.rb:47
OAuth2::DEFAULT_CONFIG = T.let(T.unsafe(nil), SnakyHash::SymbolKeyed)

# Represents an OAuth2 error condition.
#
# Wraps details from an OAuth2::Response or Hash payload returned by an
# authorization server, exposing error code and description per RFC 6749.
#
# pkg:gem/oauth2#lib/oauth2/error.rb:8
class OAuth2::Error < ::StandardError
  # Create a new OAuth2::Error
  #
  # @param response [OAuth2::Response, Hash, Object] A Response or error payload
  # @return [Error] a new instance of Error
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:18
  def initialize(response); end

  # @return [OAuth2::Response, Hash, Object] Original response or payload used to build the error
  # @return [String] Raw body content (if available)
  # @return [String, nil] Error code (e.g., 'invalid_grant')
  # @return [String, nil] Human-readable description for the error
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:13
  def body; end

  # @return [OAuth2::Response, Hash, Object] Original response or payload used to build the error
  # @return [String] Raw body content (if available)
  # @return [String, nil] Error code (e.g., 'invalid_grant')
  # @return [String, nil] Human-readable description for the error
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:13
  def code; end

  # @return [OAuth2::Response, Hash, Object] Original response or payload used to build the error
  # @return [String] Raw body content (if available)
  # @return [String, nil] Error code (e.g., 'invalid_grant')
  # @return [String, nil] Human-readable description for the error
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:13
  def description; end

  # @return [OAuth2::Response, Hash, Object] Original response or payload used to build the error
  # @return [String] Raw body content (if available)
  # @return [String, nil] Error code (e.g., 'invalid_grant')
  # @return [String, nil] Human-readable description for the error
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:13
  def response; end

  private

  # Builds a multi-line error message including description and raw body.
  #
  # @param opts [Hash] Options including :error_description
  # @param response_body [String, #encode] Response body content
  # @return [String] Message suitable for StandardError
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:45
  def error_message(response_body, opts = T.unsafe(nil)); end

  # Formats the OAuth2 error code and description into a single string.
  #
  # @param code [String, nil] OAuth2 error code
  # @param description [String, nil] OAuth2 error description
  # @return [Hash] Options hash containing :error_description when present
  #
  # pkg:gem/oauth2#lib/oauth2/error.rb:67
  def parse_error_description(code, description); end
end

# Mixin that redacts sensitive instance variables in #inspect output.
#
# Classes include this module and declare which attributes should be filtered
# using {.filtered_attributes}. Any instance variable name that includes one of
# those attribute names will be shown as [FILTERED] in the object's inspect.
#
# pkg:gem/oauth2#lib/oauth2/filtered_attributes.rb:7
module OAuth2::FilteredAttributes
  mixes_in_class_methods ::OAuth2::FilteredAttributes::ClassMethods

  # Custom inspect that redacts configured attributes.
  #
  # @return [String]
  #
  # pkg:gem/oauth2#lib/oauth2/filtered_attributes.rb:38
  def inspect; end

  class << self
    # Hook invoked when the module is included. Extends the including class with
    # class-level helpers.
    #
    # @param base [Class] The including class
    # @return [void]
    #
    # pkg:gem/oauth2#lib/oauth2/filtered_attributes.rb:13
    def included(base); end
  end
end

# Class-level helpers for configuring filtered attributes.
#
# pkg:gem/oauth2#lib/oauth2/filtered_attributes.rb:18
module OAuth2::FilteredAttributes::ClassMethods
  # The configured attribute names to filter.
  #
  # @return [Array<Symbol>]
  #
  # pkg:gem/oauth2#lib/oauth2/filtered_attributes.rb:30
  def filtered_attribute_names; end

  # Declare attributes that should be redacted in inspect output.
  #
  # @param attributes [Array<Symbol, String>] One or more attribute names
  # @return [void]
  #
  # pkg:gem/oauth2#lib/oauth2/filtered_attributes.rb:23
  def filtered_attributes(*attributes); end
end

# When true, enables verbose HTTP logging via Faraday's logger middleware.
# Controlled by the OAUTH_DEBUG environment variable. Any case-insensitive
# value equal to "true" will enable debugging.
#
# @return [Boolean]
#
# pkg:gem/oauth2#lib/oauth2.rb:36
OAuth2::OAUTH_DEBUG = T.let(T.unsafe(nil), FalseClass)

# The Response class handles HTTP responses in the OAuth2 gem, providing methods
# to access and parse response data in various formats.
#
# @since 1.0.0
#
# pkg:gem/oauth2#lib/oauth2/response.rb:12
class OAuth2::Response
  # Initializes a Response instance
  #
  # @option options
  # @option options
  # @option options
  # @param options [Hash] Additional options for the response
  # @param parse [Symbol] (:automatic) How to parse the response body
  # @param response [Faraday::Response] The Faraday response instance
  # @param snaky [Boolean] (true) Whether to convert parsed response to snake_case using SnakyHash
  # @param snaky_hash_klass [Class, nil] (nil) Custom class for snake_case hash conversion
  # @return [OAuth2::Response] The new Response instance
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:72
  def initialize(response, parse: T.unsafe(nil), snaky: T.unsafe(nil), snaky_hash_klass: T.unsafe(nil), **options); end

  # The HTTP response body
  #
  # @return [String] The response body or empty string if nil
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:98
  def body; end

  # Determines the content type of the response
  #
  # @return [String, nil] The content type or nil if headers are not present
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:132
  def content_type; end

  # The HTTP response headers
  #
  # @return [Hash] The response headers
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:84
  def headers; end

  # @return [Hash] The options hash for this instance
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:26
  def options; end

  # @return [Hash] The options hash for this instance
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:26
  def options=(_arg0); end

  # The parsed response body
  #
  # @return [Object, SnakyHash::StringKeyed] The parsed response body
  # @return [nil] If no parser is available
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:106
  def parsed; end

  # Determines the parser to be used for the response body
  #
  # @note The parser can be supplied as the +:parse+ option in the form of a Proc
  #   (or other Object responding to #call) or a Symbol. In the latter case,
  #   the actual parser will be looked up in {@@parsers} by the supplied Symbol.
  # @note If no +:parse+ option is supplied, the lookup Symbol will be determined
  #   by looking up {#content_type} in {@@content_types}.
  # @note If {#parser} is a Proc, it will be called with no arguments, just
  #   {#body}, or {#body} and {#response}, depending on the Proc's arity.
  # @return [Proc, #call] The parser proc or callable object
  # @return [nil] If no suitable parser is found
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:152
  def parser; end

  # @return [Faraday::Response] The raw Faraday response object
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:23
  def response; end

  # The HTTP response status code
  #
  # @return [Integer] The response status code
  # @since 1.0.0
  #
  # pkg:gem/oauth2#lib/oauth2/response.rb:91
  def status; end

  class << self
    # Adds a new content type parser.
    #
    # @param key [Symbol] A descriptive symbol key such as :json or :query
    # @param mime_types [Array<String>, String] One or more mime types to which this parser applies
    # @return [void]
    # @since 1.0.0
    # @yield [String] Block that will be called to parse the response body
    # @yieldparam body [String] The response body to parse
    #
    # pkg:gem/oauth2#lib/oauth2/response.rb:53
    def register_parser(key, mime_types, &block); end
  end
end

# Default configuration options for Response instances
#
# @return [Hash] The default options hash
# @since 1.0.0
#
# pkg:gem/oauth2#lib/oauth2/response.rb:16
OAuth2::Response::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/oauth2#lib/oauth2/strategy/base.rb:4
module OAuth2::Strategy; end

# The Client Assertion Strategy
#
# Sample usage:
#   client = OAuth2::Client.new(client_id, client_secret,
#                               :site => 'http://localhost:8080',
#                               :auth_scheme => :request_body)
#
#   claim_set = {
#     :iss => "http://localhost:3001",
#     :aud => "http://localhost:8080/oauth2/token",
#     :sub => "me@example.com",
#     :exp => Time.now.utc.to_i + 3600,
#   }
#
#   encoding = {
#     :algorithm => 'HS256',
#     :key => 'secret_key',
#   }
#
#   access = client.assertion.get_token(claim_set, encoding)
#   access.token                 # actual access_token string
#   access.get("/api/stuff")     # making api calls with access token in header
#
# @see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-10#section-4.1.3
#
# pkg:gem/oauth2#lib/oauth2/strategy/assertion.rb:32
class OAuth2::Strategy::Assertion < ::OAuth2::Strategy::Base
  # Not used for this strategy
  #
  # @raise [NotImplementedError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/assertion.rb:36
  def authorize_url; end

  # Retrieve an access token given the specified client.
  #
  # For reading on JWT and claim keys:
  #   @see https://github.com/jwt/ruby-jwt
  #   @see https://datatracker.ietf.org/doc/html/rfc7519#section-4.1
  #   @see https://datatracker.ietf.org/doc/html/rfc7523#section-3
  #   @see https://www.iana.org/assignments/jwt/jwt.xhtml
  #
  # There are many possible claim keys, and applications may ask for their own custom keys.
  # Some typically required ones:
  #   :iss (issuer)
  #   :aud (audience)
  #   :sub (subject) -- formerly :prn https://datatracker.ietf.org/doc/html/draft-ietf-oauth-json-web-token-06#appendix-F
  #   :exp, (expiration time) -- in seconds, e.g. Time.now.utc.to_i + 3600
  #
  # Note that this method does *not* validate presence of those four claim keys indicated as required by RFC 7523.
  # There are endpoints that may not conform with this RFC, and this gem should still work for those use cases.
  #
  # These two options are passed directly to `JWT.encode`.  For supported encoding arguments:
  #   @see https://github.com/jwt/ruby-jwt#algorithms-and-usage
  #   @see https://datatracker.ietf.org/doc/html/rfc7518#section-3.1
  #
  # The object type of `:key` may depend on the value of `:algorithm`.  Sample arguments:
  #   `get_token(claim_set, {:algorithm => 'HS256', :key => 'secret_key'})`
  #   `get_token(claim_set, {:algorithm => 'RS256', :key => OpenSSL::PKCS12.new(File.read('my_key.p12'), 'not_secret')})`
  #
  # @option algorithm
  # @option key
  # @option request_opts
  # @param algorithm [Hash] a customizable set of options
  # @param claims [Hash] the hash representation of the claims that should be encoded as a JWT (JSON Web Token)
  # @param encoding_opts [Hash] a hash containing instructions on how the JWT should be encoded
  # @param key [Hash] a customizable set of options
  # @param request_opts [Hash] options that will be used to assemble the request
  # @param response_opts [Hash] this will be merged with the token response to create the AccessToken object
  #   @see the access_token_opts argument to Client#get_token
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/assertion.rb:79
  def get_token(claims, encoding_opts, request_opts = T.unsafe(nil), response_opts = T.unsafe(nil)); end

  private

  # @raise [ArgumentError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/assertion.rb:95
  def build_assertion(claims, encoding_opts); end

  # pkg:gem/oauth2#lib/oauth2/strategy/assertion.rb:88
  def build_request(assertion, request_opts = T.unsafe(nil)); end
end

# The Authorization Code Strategy
#
# OAuth 2.1 notes:
# - PKCE is required for all OAuth clients using the authorization code flow (especially public clients).
#   This library does not enforce PKCE generation/verification; implement PKCE in your application when required.
# - Redirect URIs must be compared using exact string matching by the Authorization Server.
#   This client forwards redirect_uri but does not perform server-side validation.
#
# References:
# - OAuth 2.1 draft: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-13
# - OAuth for native apps (RFC 8252) and PKCE (RFC 7636)
#
# @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-15#section-4.1
#
# pkg:gem/oauth2#lib/oauth2/strategy/auth_code.rb:18
class OAuth2::Strategy::AuthCode < ::OAuth2::Strategy::Base
  # The required query parameters for the authorize URL
  #
  # @param params [Hash] additional query parameters
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/auth_code.rb:22
  def authorize_params(params = T.unsafe(nil)); end

  # The authorization URL endpoint of the provider
  #
  # @param params [Hash] additional query parameters for the URL
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/auth_code.rb:29
  def authorize_url(params = T.unsafe(nil)); end

  # Retrieve an access token given the specified validation code.
  #
  # @note that you must also provide a :redirect_uri with most OAuth 2.0 providers
  # @param code [String] The Authorization Code value
  # @param opts [Hash] access_token_opts, @see Client#get_token
  # @param params [Hash] additional params
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/auth_code.rb:40
  def get_token(code, params = T.unsafe(nil), opts = T.unsafe(nil)); end

  private

  # @raise [ArgumentError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/auth_code.rb:52
  def assert_valid_params(params); end
end

# pkg:gem/oauth2#lib/oauth2/strategy/base.rb:5
class OAuth2::Strategy::Base
  # @return [Base] a new instance of Base
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/base.rb:6
  def initialize(client); end
end

# The Client Credentials Strategy
#
# @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-15#section-4.4
#
# pkg:gem/oauth2#lib/oauth2/strategy/client_credentials.rb:8
class OAuth2::Strategy::ClientCredentials < ::OAuth2::Strategy::Base
  # Not used for this strategy
  #
  # @raise [NotImplementedError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/client_credentials.rb:12
  def authorize_url; end

  # Retrieve an access token given the specified client.
  #
  # @param opts [Hash] options
  # @param params [Hash] additional params
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/client_credentials.rb:20
  def get_token(params = T.unsafe(nil), opts = T.unsafe(nil)); end
end

# The Implicit Strategy
#
# IMPORTANT (OAuth 2.1): The Implicit grant (response_type=token) is omitted from the OAuth 2.1 draft specification.
# It remains here for backward compatibility with OAuth 2.0 providers. Prefer the Authorization Code flow with PKCE.
#
# References:
# - OAuth 2.1 draft: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-13
# - Why drop implicit: https://aaronparecki.com/2019/12/12/21/its-time-for-oauth-2-dot-1
# - Background: https://fusionauth.io/learn/expert-advice/oauth/differences-between-oauth-2-oauth-2-1/
#
# @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-26#section-4.2
#
# pkg:gem/oauth2#lib/oauth2/strategy/implicit.rb:16
class OAuth2::Strategy::Implicit < ::OAuth2::Strategy::Base
  # The required query parameters for the authorize URL
  #
  # @param params [Hash] additional query parameters
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/implicit.rb:20
  def authorize_params(params = T.unsafe(nil)); end

  # The authorization URL endpoint of the provider
  #
  # @param params [Hash] additional query parameters for the URL
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/implicit.rb:27
  def authorize_url(params = T.unsafe(nil)); end

  # Not used for this strategy
  #
  # @raise [NotImplementedError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/implicit.rb:35
  def get_token(*_arg0); end

  private

  # @raise [ArgumentError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/implicit.rb:41
  def assert_valid_params(params); end
end

# The Resource Owner Password Credentials Authorization Strategy
#
# IMPORTANT (OAuth 2.1): The Resource Owner Password Credentials grant is omitted in OAuth 2.1.
# It remains here for backward compatibility with OAuth 2.0 providers. Prefer Authorization Code + PKCE.
#
# References:
# - OAuth 2.1 draft: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-13
# - Okta explainer: https://developer.okta.com/blog/2019/12/13/oauth-2-1-how-many-rfcs
# - FusionAuth blog: https://fusionauth.io/blog/2020/04/15/whats-new-in-oauth-2-1
#
# @see http://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-15#section-4.3
#
# pkg:gem/oauth2#lib/oauth2/strategy/password.rb:16
class OAuth2::Strategy::Password < ::OAuth2::Strategy::Base
  # Not used for this strategy
  #
  # @raise [NotImplementedError]
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/password.rb:20
  def authorize_url; end

  # Retrieve an access token given the specified End User username and password.
  #
  # @param params [Hash] additional params
  # @param password [String] the End User password
  # @param username [String] the End User username
  #
  # pkg:gem/oauth2#lib/oauth2/strategy/password.rb:29
  def get_token(username, password, params = T.unsafe(nil), opts = T.unsafe(nil)); end
end

# pkg:gem/oauth2#lib/oauth2/client.rb:17
class OAuth2::TimeoutError < ::Faraday::TimeoutError; end

# pkg:gem/oauth2#lib/oauth2/version.rb:4
module OAuth2::Version
  extend ::VersionGem::Basic
  extend ::VersionGem::Api
end

# pkg:gem/oauth2#lib/oauth2/version.rb:5
OAuth2::Version::VERSION = T.let(T.unsafe(nil), String)
