# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-microsoft_graph` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-microsoft_graph`.


# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:6
module OmniAuth; end

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:7
module OmniAuth::MicrosoftGraph; end

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:12
OmniAuth::MicrosoftGraph::COMMON_JWKS_URL = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:14
class OmniAuth::MicrosoftGraph::DomainVerificationError < ::OmniAuth::Error; end

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:16
class OmniAuth::MicrosoftGraph::DomainVerifier
  # @return [DomainVerifier] a new instance of DomainVerifier
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:21
  def initialize(auth_hash, access_token, options); end

  # @raise [DomainVerificationError]
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:29
  def verify!; end

  private

  # Returns the value of attribute access_token.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:49
  def access_token; end

  # https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims-reference
  # Microsoft offers an optional claim `xms_edov` that will indicate whether the
  # user's email domain is part of the organization's verified domains. This has to be
  # explicitly configured in the app registration.
  #
  # To get to it, we need to decode the ID token with the key material from Microsoft's
  # OIDC configuration endpoint, and inspect it for the claim in question.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:63
  def domain_verified_jwt_claim; end

  # Returns the value of attribute email_domain.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:49
  def email_domain; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:79
  def get_jwks(oidc_config); end

  # Returns the value of attribute id_token.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:49
  def id_token; end

  # Returns the value of attribute permitted_domains.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:49
  def permitted_domains; end

  # Returns the value of attribute skip_verification.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:49
  def skip_verification; end

  # Returns the value of attribute upn_domain.
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:49
  def upn_domain; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:87
  def verification_error_message; end

  # @return [Boolean]
  #
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:73
  def xms_edov_valid?(decoded_token); end

  class << self
    # pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:17
    def verify!(auth_hash, access_token, options); end
  end
end

# Verify user email domains to mitigate the nOAuth vulnerability
# https://www.descope.com/blog/post/noauth
# https://clerk.com/docs/authentication/social-connections/microsoft#stay-secure-against-the-n-o-auth-vulnerability
#
# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/domain_verifier.rb:11
OmniAuth::MicrosoftGraph::OIDC_CONFIG_URL = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/microsoft_graph/version.rb:3
OmniAuth::MicrosoftGraph::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:4
module OmniAuth::Strategies; end

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:5
class OmniAuth::Strategies::MicrosoftGraph < ::OmniAuth::Strategies::OAuth2
  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:49
  def auth_hash; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:55
  def authorize_params; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:83
  def build_access_token; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:72
  def callback_url; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:76
  def custom_build_access_token; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:89
  def determine_profile_endpoint(request); end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:85
  def profile_endpoint; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:68
  def raw_info; end

  private

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:122
  def client_get_token(verifier, redirect_uri); end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:101
  def get_access_token(request); end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:134
  def get_scope(params); end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:130
  def get_token_options(redirect_uri = T.unsafe(nil)); end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:126
  def get_token_params; end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:149
  def verify_email(auth_hash, access_token); end

  # pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:141
  def verify_token(access_token); end
end

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:7
OmniAuth::Strategies::MicrosoftGraph::BASE_SCOPES = T.let(T.unsafe(nil), Array)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:6
OmniAuth::Strategies::MicrosoftGraph::BASE_SCOPE_URL = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:8
OmniAuth::Strategies::MicrosoftGraph::DEFAULT_SCOPE = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:10
OmniAuth::Strategies::MicrosoftGraph::MICROSOFT_GRAPH_PROFILE_URL = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-microsoft_graph#lib/omniauth/strategies/microsoft_graph.rb:9
OmniAuth::Strategies::MicrosoftGraph::YAMMER_PROFILE_URL = T.let(T.unsafe(nil), String)
