# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `polyfill` gem.
# Please instead update this file by running `bin/tapioca gem polyfill`.


class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # pkg:gem/polyfill#lib/polyfill.rb:66
  def Polyfill(options = T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/version.rb:1
module Polyfill
  private

  # pkg:gem/polyfill#lib/polyfill.rb:7
  def get(module_name, methods, options = T.unsafe(nil)); end

  class << self
    # pkg:gem/polyfill#lib/polyfill.rb:63
    def get(module_name, methods, options = T.unsafe(nil)); end
  end
end

# pkg:gem/polyfill#lib/polyfill/internal_utils.rb:2
module Polyfill::InternalUtils
  private

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:86
  def create_module(*args); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:12
  def current_ruby_version; end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:17
  def ignore_warnings; end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:41
  def keep_only_these_methods!(mod, whitelist); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:74
  def methods_to_keep(modules, methods, lead_symbol, module_name); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:48
  def modules_to_use(module_name, versions); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:99
  def namify_arguments(*args); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:27
  def polyfill_versions_to_use(desired_version = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:136
  def to_f(obj); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:149
  def to_hash(obj); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:123
  def to_int(obj); end

  # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:110
  def to_str(obj); end

  class << self
    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:97
    def create_module(*args); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:15
    def current_ruby_version; end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:25
    def ignore_warnings; end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:46
    def keep_only_these_methods!(mod, whitelist); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:84
    def methods_to_keep(modules, methods, lead_symbol, module_name); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:72
    def modules_to_use(module_name, versions); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:108
    def namify_arguments(*args); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:39
    def polyfill_versions_to_use(desired_version = T.unsafe(nil)); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:147
    def to_f(obj); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:160
    def to_hash(obj); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:134
    def to_int(obj); end

    # pkg:gem/polyfill#lib/polyfill/internal_utils.rb:121
    def to_str(obj); end
  end
end

# pkg:gem/polyfill#lib/polyfill/internal_utils.rb:3
Polyfill::InternalUtils::VERSIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/polyfill#lib/polyfill.rb:5
module Polyfill::Module; end

# pkg:gem/polyfill#lib/polyfill/v2_4/enumerable.rb:6
module Polyfill::Module::Me051bWVyaWM6IFsiI2R1cCJdLCB2ZXJzaW9uOiAiMi40In0_; end

# pkg:gem/polyfill#lib/polyfill/v2_4/enumerator/lazy.rb:5
module Polyfill::Module::Me0VudW1lcmFibGU6IFsiI2NodW5rX3doaWxlIl0sIHZlcnNpb246ICIyLjQifQ__; end

# pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:6
module Polyfill::Module::Me0ludGVnZXI6IFsiI2NlaWwiLCAiI2Zsb29yIiwgIiNyb3VuZCIsICIjdHJ1bmNhdGUiXSwgdmVyc2lvbjogIjIuNCJ9; end

# pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:4
module Polyfill::Module::Me0tlcm5lbDogWyIjeWllbGRfc2VsZiJdLCB2ZXJzaW9uOiAiMi41In0_; end

# pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:2
module Polyfill::V2_2; end

# pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:3
module Polyfill::V2_2::Enumerable
  # @raise [ArgumentError]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:4
  def max(n = T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:12
  def max_by(n = T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:22
  def min(n = T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:30
  def min_by(n = T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:40
  def slice_after(pattern = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_2/enumerable.rb:61
  def slice_when; end
end

# pkg:gem/polyfill#lib/polyfill/v2_2/kernel.rb:3
module Polyfill::V2_2::Kernel
  # pkg:gem/polyfill#lib/polyfill/v2_2/kernel.rb:4
  def itself; end
end

# pkg:gem/polyfill#lib/polyfill/v2_2/math.rb:3
module Polyfill::V2_2::Math; end

# pkg:gem/polyfill#lib/polyfill/v2_2/math.rb:4
module Polyfill::V2_2::Math::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_2/math.rb:5
  def log(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_2/prime.rb:3
module Polyfill::V2_2::Prime; end

# pkg:gem/polyfill#lib/polyfill/v2_2/prime.rb:4
module Polyfill::V2_2::Prime::ClassMethods
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_2/prime.rb:5
  def prime?(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_2/vector.rb:3
module Polyfill::V2_2::Vector
  # pkg:gem/polyfill#lib/polyfill/v2_2/vector.rb:4
  def +@; end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/array.rb:2
module Polyfill::V2_3; end

# pkg:gem/polyfill#lib/polyfill/v2_3/array.rb:3
module Polyfill::V2_3::Array
  # pkg:gem/polyfill#lib/polyfill/v2_3/array.rb:4
  def bsearch_index; end

  # pkg:gem/polyfill#lib/polyfill/v2_3/array.rb:14
  def dig(head, *rest); end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/enumerable.rb:3
module Polyfill::V2_3::Enumerable
  # pkg:gem/polyfill#lib/polyfill/v2_3/enumerable.rb:4
  def chunk_while; end

  # pkg:gem/polyfill#lib/polyfill/v2_3/enumerable.rb:23
  def grep_v(pattern); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/enumerable.rb:29
  def slice_before(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/enumerator/lazy.rb:3
module Polyfill::V2_3::Enumerator; end

# pkg:gem/polyfill#lib/polyfill/v2_3/enumerator/lazy.rb:4
module Polyfill::V2_3::Enumerator::Lazy
  # pkg:gem/polyfill#lib/polyfill/v2_3/enumerator/lazy.rb:5
  def grep_v(pattern); end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:3
module Polyfill::V2_3::Hash
  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:4
  def <(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:12
  def <=(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:18
  def >(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:26
  def >=(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:32
  def dig(head, *rest); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:55
  def fetch_values(*keys); end

  # pkg:gem/polyfill#lib/polyfill/v2_3/hash.rb:69
  def to_proc; end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/kernel.rb:3
module Polyfill::V2_3::Kernel
  # pkg:gem/polyfill#lib/polyfill/v2_3/kernel.rb:4
  def loop; end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/numeric.rb:3
module Polyfill::V2_3::Numeric
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_3/numeric.rb:4
  def negative?; end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_3/numeric.rb:8
  def positive?; end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/prime.rb:3
module Polyfill::V2_3::Prime; end

# pkg:gem/polyfill#lib/polyfill/v2_3/prime.rb:4
module Polyfill::V2_3::Prime::ClassMethods
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_3/prime.rb:5
  def prime?(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/string.rb:3
module Polyfill::V2_3::String
  # pkg:gem/polyfill#lib/polyfill/v2_3/string.rb:20
  def +@; end

  # pkg:gem/polyfill#lib/polyfill/v2_3/string.rb:24
  def -@; end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/string.rb:4
module Polyfill::V2_3::String::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_3/string.rb:5
  def new(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_3/struct.rb:3
module Polyfill::V2_3::Struct
  # pkg:gem/polyfill#lib/polyfill/v2_3/struct.rb:4
  def dig(head, *rest); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/numeric.rb:2
module Polyfill::V2_4; end

# pkg:gem/polyfill#lib/polyfill/v2_4/array.rb:5
module Polyfill::V2_4::Array
  # pkg:gem/polyfill#lib/polyfill/v2_4/array.rb:8
  def concat(*others); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/array.rb:19
  def sum(init = T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/comparable.rb:3
module Polyfill::V2_4::Comparable
  # pkg:gem/polyfill#lib/polyfill/v2_4/comparable.rb:4
  def clamp(min, max); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/dir.rb:3
module Polyfill::V2_4::Dir; end

# pkg:gem/polyfill#lib/polyfill/v2_4/dir.rb:4
module Polyfill::V2_4::Dir::ClassMethods
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/dir.rb:5
  def empty?(path_name); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/enumerable.rb:5
module Polyfill::V2_4::Enumerable
  # pkg:gem/polyfill#lib/polyfill/v2_4/enumerable.rb:8
  def chunk(*_arg0); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/enumerable.rb:14
  def sum(init = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/enumerable.rb:24
  def uniq; end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/enumerator/lazy.rb:3
module Polyfill::V2_4::Enumerator; end

# pkg:gem/polyfill#lib/polyfill/v2_4/enumerator/lazy.rb:4
module Polyfill::V2_4::Enumerator::Lazy
  # pkg:gem/polyfill#lib/polyfill/v2_4/enumerator/lazy.rb:7
  def chunk_while; end

  # pkg:gem/polyfill#lib/polyfill/v2_4/enumerator/lazy.rb:11
  def uniq; end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/file.rb:3
module Polyfill::V2_4::File; end

# pkg:gem/polyfill#lib/polyfill/v2_4/file.rb:4
module Polyfill::V2_4::File::ClassMethods
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/file.rb:5
  def empty?(file_name); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/float.rb:3
module Polyfill::V2_4::Float
  # pkg:gem/polyfill#lib/polyfill/v2_4/float.rb:4
  def ceil(ndigits = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/float.rb:17
  def floor(ndigits = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/float.rb:30
  def truncate(ndigits = T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/hash.rb:3
module Polyfill::V2_4::Hash
  # pkg:gem/polyfill#lib/polyfill/v2_4/hash.rb:4
  def compact; end

  # pkg:gem/polyfill#lib/polyfill/v2_4/hash.rb:8
  def compact!; end

  # pkg:gem/polyfill#lib/polyfill/v2_4/hash.rb:12
  def transform_values; end

  # pkg:gem/polyfill#lib/polyfill/v2_4/hash.rb:26
  def transform_values!; end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:5
module Polyfill::V2_4::IO
  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:58
  def each_line(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:91
  def gets(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:107
  def lines(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:140
  def readline(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:156
  def readlines(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:6
module Polyfill::V2_4::IO::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:7
  def foreach(name, *args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/io.rb:41
  def readlines(file_name, *args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/i_p_addr.rb:3
module Polyfill::V2_4::IPAddr
  # pkg:gem/polyfill#lib/polyfill/v2_4/i_p_addr.rb:10
  def <=>(*_arg0); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/i_p_addr.rb:4
  def ==(*_arg0); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/integer.rb:3
module Polyfill::V2_4::Integer
  # pkg:gem/polyfill#lib/polyfill/v2_4/integer.rb:4
  def ceil(ndigits = T.unsafe(nil)); end

  # @raise [Math::DomainError]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/integer.rb:13
  def digits(base = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/integer.rb:28
  def floor(ndigits = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/integer.rb:37
  def round(ndigits = T.unsafe(nil), half: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/integer.rb:49
  def truncate(ndigits = T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/match_data.rb:3
module Polyfill::V2_4::MatchData
  # pkg:gem/polyfill#lib/polyfill/v2_4/match_data.rb:4
  def named_captures; end

  # pkg:gem/polyfill#lib/polyfill/v2_4/match_data.rb:10
  def values_at(*indexes); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/numeric.rb:3
module Polyfill::V2_4::Numeric
  # pkg:gem/polyfill#lib/polyfill/v2_4/numeric.rb:4
  def clone(freeze: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/numeric.rb:8
  def dup; end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/numeric.rb:12
  def finite?; end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/numeric.rb:16
  def infinite?; end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/object.rb:3
module Polyfill::V2_4::Object
  # pkg:gem/polyfill#lib/polyfill/v2_4/object.rb:4
  def clone(freeze: T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/pathname.rb:3
module Polyfill::V2_4::Pathname
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/pathname.rb:4
  def empty?; end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/regexp.rb:3
module Polyfill::V2_4::Regexp
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/regexp.rb:4
  def match?(string, position = T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:5
module Polyfill::V2_4::String
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:15
  def casecmp?(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:19
  def concat(*others); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:30
  def each_line(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:63
  def lines(*args); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:97
  def match?(pattern, position = T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:101
  def prepend(*others); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:112
  def unpack1(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:6
module Polyfill::V2_4::String::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_4/string.rb:7
  def new(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:5
module Polyfill::V2_4::StringIO
  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:58
  def each_line(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:91
  def gets(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:107
  def lines(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:140
  def readline(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:156
  def readlines(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:6
module Polyfill::V2_4::StringIO::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:7
  def foreach(name, *args); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/string_io.rb:41
  def readlines(file_name, *args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_4/symbol.rb:3
module Polyfill::V2_4::Symbol
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/symbol.rb:4
  def casecmp?(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_4/symbol.rb:10
  def match(*args); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_4/symbol.rb:18
  def match?(pattern, position = T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/array.rb:2
module Polyfill::V2_5; end

# pkg:gem/polyfill#lib/polyfill/v2_5/array.rb:3
module Polyfill::V2_5::Array
  # pkg:gem/polyfill#lib/polyfill/v2_5/array.rb:4
  def append(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/array.rb:8
  def prepend(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/big_decimal.rb:3
module Polyfill::V2_5::BigDecimal
  # pkg:gem/polyfill#lib/polyfill/v2_5/big_decimal.rb:4
  def clone; end

  # pkg:gem/polyfill#lib/polyfill/v2_5/big_decimal.rb:8
  def dup; end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/dir.rb:3
module Polyfill::V2_5::Dir; end

# pkg:gem/polyfill#lib/polyfill/v2_5/dir.rb:4
module Polyfill::V2_5::Dir::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_5/dir.rb:5
  def children(dirname, encoding: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/dir.rb:9
  def each_child(dirname, encoding: T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/enumerable.rb:3
module Polyfill::V2_5::Enumerable
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/enumerable.rb:4
  def all?(*pattern); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/enumerable.rb:10
  def any?(*pattern); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/enumerable.rb:16
  def none?(*pattern); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/enumerable.rb:22
  def one?(*pattern); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/hash.rb:3
module Polyfill::V2_5::Hash
  # pkg:gem/polyfill#lib/polyfill/v2_5/hash.rb:4
  def slice(*keys); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/hash.rb:10
  def transform_keys; end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:5
module Polyfill::V2_5::Integer
  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:52
  def allbits?(mask); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:57
  def anybits?(mask); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:36
  def ceil(*_arg0); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:40
  def floor(*_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:61
  def nobits?(mask); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:44
  def round(*_arg0); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:48
  def truncate(*_arg0); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:8
module Polyfill::V2_5::Integer::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_5/integer.rb:9
  def sqrt(n); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/kernel.rb:3
module Polyfill::V2_5::Kernel
  # @yield [_self]
  # @yieldparam _self [Polyfill::V2_5::Kernel] the object that the method was called on
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/kernel.rb:4
  def yield_self; end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/set.rb:3
module Polyfill::V2_5::Set
  # pkg:gem/polyfill#lib/polyfill/v2_5/set.rb:4
  def ===(other); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/set.rb:8
  def to_s; end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:3
module Polyfill::V2_5::String
  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:4
  def casecmp(other_str); end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:10
  def casecmp?(other_str); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:16
  def delete_prefix(prefix); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:20
  def delete_prefix!(prefix); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:26
  def delete_suffix(suffix); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:30
  def delete_suffix!(suffix); end

  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:48
  def each_grapheme_cluster; end

  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:42
  def grapheme_clusters; end

  # @return [Boolean]
  #
  # pkg:gem/polyfill#lib/polyfill/v2_5/string.rb:34
  def start_with?(*prefixes); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/struct.rb:3
module Polyfill::V2_5::Struct; end

# pkg:gem/polyfill#lib/polyfill/v2_5/struct.rb:4
module Polyfill::V2_5::Struct::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_5/struct.rb:5
  def new(*args, keyword_init: T.unsafe(nil)); end
end

# pkg:gem/polyfill#lib/polyfill/v2_5/time.rb:3
module Polyfill::V2_5::Time; end

# pkg:gem/polyfill#lib/polyfill/v2_5/time.rb:4
module Polyfill::V2_5::Time::ClassMethods
  # pkg:gem/polyfill#lib/polyfill/v2_5/time.rb:5
  def at(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/array.rb:2
module Polyfill::V2_6; end

# pkg:gem/polyfill#lib/polyfill/v2_6/array.rb:3
module Polyfill::V2_6::Array
  # pkg:gem/polyfill#lib/polyfill/v2_6/array.rb:4
  def difference(*arrays); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/array.rb:10
  def to_h; end

  # pkg:gem/polyfill#lib/polyfill/v2_6/array.rb:34
  def union(*arrays); end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/enumerable.rb:3
module Polyfill::V2_6::Enumerable
  # pkg:gem/polyfill#lib/polyfill/v2_6/enumerable.rb:4
  def to_h; end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/hash.rb:3
module Polyfill::V2_6::Hash
  # pkg:gem/polyfill#lib/polyfill/v2_6/hash.rb:28
  def merge(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/hash.rb:40
  def merge!(*args); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/hash.rb:4
  def to_h; end

  # pkg:gem/polyfill#lib/polyfill/v2_6/hash.rb:52
  def update(*args); end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:3
module Polyfill::V2_6::Kernel
  # pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:6
  def Complex(*args, exception: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:21
  def Float(arg, exception: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:31
  def Integer(arg, exception: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:41
  def Rational(*args, exception: T.unsafe(nil)); end

  # pkg:gem/polyfill#lib/polyfill/v2_6/kernel.rb:51
  def then; end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/open_struct.rb:5
module Polyfill::V2_6::OpenStruct
  # pkg:gem/polyfill#lib/polyfill/v2_6/open_struct.rb:6
  def to_h; end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/string.rb:3
module Polyfill::V2_6::String
  # pkg:gem/polyfill#lib/polyfill/v2_6/string.rb:4
  def split(*_arg0); end
end

# pkg:gem/polyfill#lib/polyfill/v2_6/struct.rb:3
module Polyfill::V2_6::Struct
  # pkg:gem/polyfill#lib/polyfill/v2_6/struct.rb:4
  def to_h; end
end

# pkg:gem/polyfill#lib/polyfill/version.rb:2
Polyfill::VERSION = T.let(T.unsafe(nil), Gem::Version)
