# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-erb` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-erb`.


# pkg:gem/rubocop-erb#lib/rubocop/erb.rb:3
module RuboCop; end

# pkg:gem/rubocop-erb#lib/rubocop/erb.rb:4
module RuboCop::Erb; end

# Remove unnecessary keyword part (e.g. `if`, `unless`, `do`, ...) from Ruby-ish code.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:6
class RuboCop::Erb::KeywordRemover
  # @param ruby_clip [RuboCop::Erb::RubyClip]
  # @return [KeywordRemover] a new instance of KeywordRemover
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:16
  def initialize(ruby_clip); end

  # @return [RuboCop::Erb::RubyClip]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:21
  def call; end

  class << self
    # @param ruby_clip [RuboCop::Erb::RubyClip]
    # @return [RuboCop::Erb::RubyClip]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:10
    def call(ruby_clip); end
  end
end

# Remove preceding `}`.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:94
class RuboCop::Erb::KeywordRemover::PrecedingBraceRemover < ::RuboCop::Erb::KeywordRemover::PrecedingSourceRemover; end

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:95
RuboCop::Erb::KeywordRemover::PrecedingBraceRemover::REGEXP = T.let(T.unsafe(nil), Regexp)

# Remove preceding keyword.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:70
class RuboCop::Erb::KeywordRemover::PrecedingKeywordRemover < ::RuboCop::Erb::KeywordRemover::PrecedingSourceRemover; end

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:71
RuboCop::Erb::KeywordRemover::PrecedingKeywordRemover::REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:37
class RuboCop::Erb::KeywordRemover::PrecedingSourceRemover
  # @param code [String]
  # @return [PrecedingSourceRemover] a new instance of PrecedingSourceRemover
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:47
  def initialize(code); end

  # @return [Hash]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:52
  def call; end

  class << self
    # @param code [String]
    # @return [RubyClip]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:41
    def call(code); end
  end
end

# Remove trailing `{`.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:126
class RuboCop::Erb::KeywordRemover::TrailingBraceRemover < ::RuboCop::Erb::KeywordRemover::TrailingSourceRemover; end

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:127
RuboCop::Erb::KeywordRemover::TrailingBraceRemover::REGEXP = T.let(T.unsafe(nil), Regexp)

# Remove trailing `do`.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:147
class RuboCop::Erb::KeywordRemover::TrailingDoRemover < ::RuboCop::Erb::KeywordRemover::TrailingSourceRemover; end

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:148
RuboCop::Erb::KeywordRemover::TrailingDoRemover::REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:102
class RuboCop::Erb::KeywordRemover::TrailingSourceRemover
  # @param code [String]
  # @return [TrailingSourceRemover] a new instance of TrailingSourceRemover
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:112
  def initialize(code); end

  # @return [Hash]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:117
  def call; end

  class << self
    # @param code [String]
    # @return [RubyClip]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:106
    def call(code); end
  end
end

# Remove trailing `then`.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:137
class RuboCop::Erb::KeywordRemover::TrailingThenRemover < ::RuboCop::Erb::KeywordRemover::TrailingSourceRemover; end

# pkg:gem/rubocop-erb#lib/rubocop/erb/keyword_remover.rb:138
RuboCop::Erb::KeywordRemover::TrailingThenRemover::REGEXP = T.let(T.unsafe(nil), Regexp)

# A plugin that integrates rubocop-erb with RuboCop's plugin system.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/plugin.rb:8
class RuboCop::Erb::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-erb#lib/rubocop/erb/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/plugin.rb:18
  def rules(_context); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/plugin.rb:28
  def supported?(context); end
end

# pkg:gem/rubocop-erb#lib/rubocop/erb/processed_source_builder.rb:5
class RuboCop::Erb::ProcessedSourceBuilder
  # @return [ProcessedSourceBuilder] a new instance of ProcessedSourceBuilder
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/processed_source_builder.rb:23
  def initialize(code:, processed_source:); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/processed_source_builder.rb:31
  def call; end

  class << self
    # Creates a new ProcessedSource, inheriting state from a donor.
    #
    # @param code [String]
    # @param processed_source [RuboCop::ProcessedSource]
    # @return [RuboCop::ProcessedSource]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/processed_source_builder.rb:12
    def call(code:, processed_source:); end
  end
end

# pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
class RuboCop::Erb::RubyClip < ::Struct
  # Returns the value of attribute code
  #
  # @return [Object] the current value of code
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
  def code; end

  # Sets the attribute code
  #
  # @param value [Object] the value to set the attribute code to.
  # @return [Object] the newly set value
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
  def code=(_); end

  # Returns the value of attribute offset
  #
  # @return [Object] the current value of offset
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
  def offset; end

  # Sets the attribute offset
  #
  # @param value [Object] the value to set the attribute offset to.
  # @return [Object] the newly set value
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
  def offset=(_); end

  class << self
    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
    def [](*_arg0); end

    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
    def inspect; end

    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
    def keyword_init?; end

    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
    def members; end

    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_clip.rb:5
    def new(*_arg0); end
  end
end

# Extract Ruby codes from Erb template.
#
# pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:9
class RuboCop::Erb::RubyExtractor
  # @param processed_source [RuboCop::ProcessedSource]
  # @return [RubyExtractor] a new instance of RubyExtractor
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:19
  def initialize(processed_source); end

  # @return [Array<RuboCop::ProcessedSource>, nil]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:24
  def call; end

  private

  # @return [String, nil]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:41
  def file_path; end

  # @return [Array<Herb::AST::Node>]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:46
  def nodes; end

  # @return [Herb::AST::DocumentNode]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:53
  def root; end

  # @return [Array<RuboCop::Erb::RubyClip>]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:58
  def ruby_clips; end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:76
  def supported_file_path_pattern?; end

  # @return [String]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:81
  def template_source; end

  class << self
    # @param processed_source [RuboCop::ProcessedSource]
    # @return [Array<RuboCop::ProcessedSource>, nil]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:13
    def call(processed_source); end
  end
end

# pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:85
class RuboCop::Erb::RubyExtractor::ErbNodeVisitor < ::Herb::Visitor
  # @return [ErbNodeVisitor] a new instance of ErbNodeVisitor
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:93
  def initialize; end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:99
  def comment?(node); end

  # Returns the value of attribute erb_nodes.
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:91
  def erb_nodes; end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:104
  def escape?(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:117
  def record_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_begin_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_block_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_case_match_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_case_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_content_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_else_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_end_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_ensure_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_for_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_if_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_in_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_open_tag_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_render_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_rescue_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_strict_locals_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_unless_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_until_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_when_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_while_node(node); end

  # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:109
  def visit_erb_yield_node(node); end

  class << self
    # @return [Array<Symbol>]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/ruby_extractor.rb:87
    def erb_visitor_methods; end
  end
end

# pkg:gem/rubocop-erb#lib/rubocop/erb/version.rb:5
RuboCop::Erb::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-erb#lib/rubocop/erb/when_decomposer.rb:5
class RuboCop::Erb::WhenDecomposer
  # @param processed_source [RuboCop::ProcessedSource]
  # @param ruby_clip [RuboCop::Erb::RubyClip]
  # @return [WhenDecomposer] a new instance of WhenDecomposer
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/when_decomposer.rb:26
  def initialize(processed_source, ruby_clip); end

  # @return [Array<RuboCop::Erb::RubyClip>]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/when_decomposer.rb:35
  def call; end

  private

  # @param source [String]
  # @return [RuboCop::AST::Node]
  #
  # pkg:gem/rubocop-erb#lib/rubocop/erb/when_decomposer.rb:63
  def parse(source); end

  class << self
    # @param processed_source [RuboCop::ProcessedSource]
    # @param ruby_clip [RuboCop::Erb::RubyClip]
    # @return [Array<RuboCop::Erb::RubyClip>]
    #
    # pkg:gem/rubocop-erb#lib/rubocop/erb/when_decomposer.rb:16
    def call(processed_source, ruby_clip); end
  end
end

# pkg:gem/rubocop-erb#lib/rubocop/erb/when_decomposer.rb:6
RuboCop::Erb::WhenDecomposer::REGEXP = T.let(T.unsafe(nil), Regexp)
