# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-lsp-rspec` gem.
# Please instead update this file by running `bin/tapioca gem ruby-lsp-rspec`.


# pkg:gem/ruby-lsp-rspec#lib/ruby_lsp_rspec/version.rb:4
module RubyLsp; end

# pkg:gem/ruby-lsp-rspec#lib/ruby_lsp_rspec/version.rb:5
module RubyLsp::RSpec; end

# pkg:gem/ruby-lsp-rspec#lib/ruby_lsp_rspec/version.rb:6
RubyLsp::RSpec::VERSION = T.let(T.unsafe(nil), String)
