# typed: false

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/flow_transforms" do
  # This should return the minimal set of attributes required to create a valid
  # FlowTransform. As you add validations to FlowTransform, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FlowTransform.create! valid_attributes
      get flow_transforms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      flow_transform = FlowTransform.create! valid_attributes
      get flow_transform_url(flow_transform)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_flow_transform_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      flow_transform = FlowTransform.create! valid_attributes
      get edit_flow_transform_url(flow_transform)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FlowTransform" do
        expect {
          post flow_transforms_url, params: { flow_transform: valid_attributes }
        }.to change(FlowTransform, :count).by(1)
      end

      it "redirects to the created flow_transform" do
        post flow_transforms_url, params: { flow_transform: valid_attributes }
        expect(response).to redirect_to(flow_transform_url(FlowTransform.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FlowTransform" do
        expect {
          post flow_transforms_url, params: { flow_transform: invalid_attributes }
        }.not_to change(FlowTransform, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post flow_transforms_url, params: { flow_transform: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flow_transform" do
        flow_transform = FlowTransform.create! valid_attributes
        patch flow_transform_url(flow_transform), params: { flow_transform: new_attributes }
        flow_transform.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the flow_transform" do
        flow_transform = FlowTransform.create! valid_attributes
        patch flow_transform_url(flow_transform), params: { flow_transform: new_attributes }
        flow_transform.reload
        expect(response).to redirect_to(flow_transform_url(flow_transform))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        flow_transform = FlowTransform.create! valid_attributes
        patch flow_transform_url(flow_transform), params: { flow_transform: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested flow_transform" do
      flow_transform = FlowTransform.create! valid_attributes
      expect {
        delete flow_transform_url(flow_transform)
      }.to change(FlowTransform, :count).by(-1)
    end

    it "redirects to the flow_transforms list" do
      flow_transform = FlowTransform.create! valid_attributes
      delete flow_transform_url(flow_transform)
      expect(response).to redirect_to(flow_transforms_url)
    end
  end
end
