# typed: false

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/flow_filters" do
  # This should return the minimal set of attributes required to create a valid
  # FlowFilter. As you add validations to FlowFilter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FlowFilter.create! valid_attributes
      get flow_filters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      flow_filter = FlowFilter.create! valid_attributes
      get flow_filter_url(flow_filter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_flow_filter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      flow_filter = FlowFilter.create! valid_attributes
      get edit_flow_filter_url(flow_filter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FlowFilter" do
        expect {
          post flow_filters_url, params: { flow_filter: valid_attributes }
        }.to change(FlowFilter, :count).by(1)
      end

      it "redirects to the created flow_filter" do
        post flow_filters_url, params: { flow_filter: valid_attributes }
        expect(response).to redirect_to(flow_filter_url(FlowFilter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FlowFilter" do
        expect {
          post flow_filters_url, params: { flow_filter: invalid_attributes }
        }.not_to change(FlowFilter, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post flow_filters_url, params: { flow_filter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flow_filter" do
        flow_filter = FlowFilter.create! valid_attributes
        patch flow_filter_url(flow_filter), params: { flow_filter: new_attributes }
        flow_filter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the flow_filter" do
        flow_filter = FlowFilter.create! valid_attributes
        patch flow_filter_url(flow_filter), params: { flow_filter: new_attributes }
        flow_filter.reload
        expect(response).to redirect_to(flow_filter_url(flow_filter))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        flow_filter = FlowFilter.create! valid_attributes
        patch flow_filter_url(flow_filter), params: { flow_filter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested flow_filter" do
      flow_filter = FlowFilter.create! valid_attributes
      expect {
        delete flow_filter_url(flow_filter)
      }.to change(FlowFilter, :count).by(-1)
    end

    it "redirects to the flow_filters list" do
      flow_filter = FlowFilter.create! valid_attributes
      delete flow_filter_url(flow_filter)
      expect(response).to redirect_to(flow_filters_url)
    end
  end
end
